#!/usr/bin/env bash
# ~/.claude/hooks/pre-commit-check.sh
#
# Claude Code PreToolUse hook — intercepts every `git commit` invocation.
# Scans staged files and diff for AI/Claude traces, then requires explicit
# confirmation before allowing the commit to proceed.
#
# Exit 0  → allow the commit
# Exit 1  → block the commit (Claude Code will not run the command)

set -euo pipefail

# ── Helpers ──────────────────────────────────────────────────────────────────

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

print_header() {
    echo ""
    echo -e "${BOLD}${CYAN}CLAUDE CODE PRE-COMMIT CHECK${RESET}"
    echo -e "${CYAN}════════════════════════════${RESET}"
}

print_issue() {
    echo -e "  ${RED}⚠  $1${RESET}"
    echo -e "     ${YELLOW}→ $2${RESET}"
}

print_ok() {
    echo -e "  ${GREEN}✓${RESET} $1"
}

# ── Gather context ────────────────────────────────────────────────────────────

# Staged file list
STAGED_FILES=$(git diff --cached --name-only 2>/dev/null || true)

# Full diff of staged content
STAGED_DIFF=$(git diff --cached 2>/dev/null || true)

# Proposed commit message (from -m flag if present, otherwise empty)
# Claude Code passes the full command as CLAUDE_TOOL_INPUT
COMMIT_CMD="${CLAUDE_TOOL_INPUT:-}"
COMMIT_MSG=""
if [[ "$COMMIT_CMD" =~ -m[[:space:]]+\"([^\"]+)\" ]]; then
    COMMIT_MSG="${BASH_REMATCH[1]}"
elif [[ "$COMMIT_CMD" =~ -m[[:space:]]+\'([^\']+)\' ]]; then
    COMMIT_MSG="${BASH_REMATCH[1]}"
fi

# ── Trace artifact patterns ───────────────────────────────────────────────────

# Files that reveal Claude Code usage
TRACE_FILE_PATTERNS=(
    "^\.claude/"
    "^\.claude$"
    "CLAUDE\.md$"
    "CLAUDE\.local\.md$"
    "\.mcp\.json$"
    "settings\.local\.json$"
)

# Keywords in diff content or commit message (case-insensitive)
TRACE_KEYWORDS=(
    "claude"
    "copilot"
    "\bai\b"
    "llm"
    "generated by"
    "co-authored-by.*claude"
    "generated with claude"
)

# ── Check 1: Trace files staged ───────────────────────────────────────────────

ISSUES=()
ISSUE_COUNT=0

while IFS= read -r file; do
    [[ -z "$file" ]] && continue
    for pattern in "${TRACE_FILE_PATTERNS[@]}"; do
        if echo "$file" | grep -qiE "$pattern"; then
            ISSUES+=("FILE|$file|This file may reveal Claude Code usage")
            (( ISSUE_COUNT++ )) || true
            break
        fi
    done
done <<< "$STAGED_FILES"

# ── Check 2: AI keywords in diff content ──────────────────────────────────────

for keyword in "${TRACE_KEYWORDS[@]}"; do
    # Search in added lines only (lines starting with +, excluding +++ header)
    matches=$(echo "$STAGED_DIFF" | grep -inE "^\+" | grep -v "^+++" | grep -iE "$keyword" || true)
    if [[ -n "$matches" ]]; then
        # Extract file and line context
        while IFS= read -r match; do
            [[ -z "$match" ]] && continue
            ISSUES+=("DIFF|$keyword|$match")
            (( ISSUE_COUNT++ )) || true
        done <<< "$(echo "$matches" | head -5)"  # cap at 5 matches per keyword
    fi
done

# ── Check 3: AI keywords in commit message ────────────────────────────────────

if [[ -n "$COMMIT_MSG" ]]; then
    for keyword in "${TRACE_KEYWORDS[@]}"; do
        if echo "$COMMIT_MSG" | grep -qiE "$keyword"; then
            ISSUES+=("MSG|$keyword|Commit message contains: $COMMIT_MSG")
            (( ISSUE_COUNT++ )) || true
        fi
    done
fi

# ── Check 4: Attribution settings ────────────────────────────────────────────

check_attribution() {
    local settings_file="$1"
    [[ ! -f "$settings_file" ]] && return
    # Check if attribution fields are non-empty strings
    if python3 -c "
import json, sys
try:
    d = json.load(open('$settings_file'))
    a = d.get('attribution', {})
    commit_attr = a.get('commit', '')
    pr_attr = a.get('pr', '')
    if commit_attr or pr_attr:
        print(f'commit={commit_attr!r} pr={pr_attr!r}')
        sys.exit(1)
except Exception:
    pass
" 2>/dev/null; then
        : # attribution is empty/disabled, ok
    else
        local attr_info
        attr_info=$(python3 -c "
import json
try:
    d = json.load(open('$settings_file'))
    a = d.get('attribution', {})
    print(f\"commit='{a.get('commit','')}' pr='{a.get('pr','')}'\" )
except Exception:
    print('unknown')
" 2>/dev/null || echo "unknown")
        ISSUES+=("ATTR|$settings_file|Attribution is enabled: $attr_info")
        (( ISSUE_COUNT++ )) || true
    fi
}

check_attribution "$HOME/.claude/settings.json"
check_attribution ".claude/settings.json"
check_attribution ".claude/settings.local.json"

# ── Output ────────────────────────────────────────────────────────────────────

print_header

if [[ $ISSUE_COUNT -gt 0 ]]; then
    echo ""
    echo -e "${RED}${BOLD}  ⚠  Issues found — commit blocked until resolved${RESET}"
    echo ""

    prev_type=""
    for issue in "${ISSUES[@]}"; do
        IFS='|' read -r type detail context <<< "$issue"

        case "$type" in
            FILE)
                [[ "$prev_type" != "FILE" ]] && echo -e "  ${BOLD}Staged files with trace artifacts:${RESET}"
                print_issue "$detail" "$context"
                ;;
            DIFF)
                [[ "$prev_type" != "DIFF" ]] && echo -e "\n  ${BOLD}AI-related content in diff:${RESET}"
                print_issue "keyword '$detail' found" "$context"
                ;;
            MSG)
                [[ "$prev_type" != "MSG" ]] && echo -e "\n  ${BOLD}AI-related content in commit message:${RESET}"
                print_issue "keyword '$detail' in message" "$context"
                ;;
            ATTR)
                [[ "$prev_type" != "ATTR" ]] && echo -e "\n  ${BOLD}Attribution settings:${RESET}"
                print_issue "$detail" "$context"
                ;;
        esac
        prev_type="$type"
    done

    echo ""
    echo -e "  ${YELLOW}Resolve each issue before committing:${RESET}"
    echo -e "  ${YELLOW}• Unstage trace files or add them to .gitignore${RESET}"
    echo -e "  ${YELLOW}• Edit AI-related comments or commit message${RESET}"
    echo -e "  ${YELLOW}• Disable attribution in settings if needed${RESET}"
    echo ""
    echo -e "  ${RED}Commit aborted.${RESET}"
    echo ""
    exit 1

else
    # Clean — show summary and ask for confirmation
    echo ""
    print_ok "No trace artifacts staged"
    print_ok "No AI-related content in diff"
    if [[ -n "$COMMIT_MSG" ]]; then
        print_ok "No AI-related content in commit message"
    fi
    print_ok "Attribution check passed"
    echo ""

    # Show what is being committed
    echo -e "  ${BOLD}Staged files:${RESET}"
    while IFS= read -r file; do
        [[ -z "$file" ]] && continue
        echo -e "    ${file}"
    done <<< "$STAGED_FILES"

    if [[ -n "$COMMIT_MSG" ]]; then
        echo ""
        echo -e "  ${BOLD}Commit message:${RESET} ${COMMIT_MSG}"
    fi

    echo ""
    echo -ne "  ${BOLD}OK to commit? [y/N]:${RESET} "
    read -r answer </dev/tty

    if [[ "$answer" =~ ^[Yy]$ ]]; then
        echo ""
        exit 0
    else
        echo ""
        echo -e "  ${YELLOW}Commit cancelled by user.${RESET}"
        echo ""
        exit 1
    fi
fi
